namespace demodulation
{
    partial class Constellation
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.PlotLab.ScopeChannel scopeChannel1 = new Mitov.PlotLab.ScopeChannel();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Constellation));
            Mitov.PlotLab.ScopePoints scopePoints1 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen1 = new Vcl.VclPen();
            Mitov.PlotLab.ScopeDataView scopeDataView1 = new Mitov.PlotLab.ScopeDataView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground1 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings1 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen2 = new Vcl.VclPen();
            Mitov.PlotLab.DataChartHighlighting dataChartHighlighting1 = new Mitov.PlotLab.DataChartHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting1 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting2 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting1 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting2 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting3 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting4 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting5 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.ChannelMouseHitPoint channelMouseHitPoint1 = new Mitov.PlotLab.ChannelMouseHitPoint();
            Mitov.BasicLab.OptionalLabel optionalLabel1 = new Mitov.BasicLab.OptionalLabel();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting6 = new Mitov.PlotLab.DisplayItemHighlighting();
            OpenWire.Proxy.PinList pinList1 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeLegendView scopeLegendView1 = new Mitov.PlotLab.ScopeLegendView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground2 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.LegendViewButtonSettings legendViewButtonSettings1 = new Mitov.PlotLab.LegendViewButtonSettings();
            Mitov.PlotLab.LegendGroup legendGroup1 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel1 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup2 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel2 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup3 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel3 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup4 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel4 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup5 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel5 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup6 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel6 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup7 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel7 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayViewSize displayViewSize1 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.LegendGroup legendGroup8 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel8 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayTitle displayTitle1 = new Mitov.PlotLab.DisplayTitle();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground3 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayViewSize displayViewSize2 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayToolBar displayToolBar1 = new Mitov.PlotLab.DisplayToolBar();
            Mitov.PlotLab.DisplayToolBarButtons displayToolBarButtons1 = new Mitov.PlotLab.DisplayToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton1 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage1 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton2 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage2 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton3 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage3 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton4 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage4 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton5 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage5 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton6 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage6 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton7 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage7 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize1 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton8 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage8 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton9 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage9 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton10 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage10 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton11 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage11 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton12 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage12 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton13 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage13 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton14 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage14 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarPosition toolBarPosition1 = new Mitov.PlotLab.ToolBarPosition();
            Mitov.PlotLab.DisplayTrails displayTrails1 = new Mitov.PlotLab.DisplayTrails();
            Mitov.PlotLab.ScopeXAxis scopeXAxis1 = new Mitov.PlotLab.ScopeXAxis();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel1 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground4 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings1 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings1 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings1 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings2 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen3 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings3 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen4 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat1 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks1 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart1 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue1 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange1 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue1 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue2 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue1 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.ScopeMaxSample scopeMaxSample1 = new Mitov.PlotLab.ScopeMaxSample();
            Mitov.PlotLab.AxisValue axisValue1 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange2 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue3 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue4 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue2 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks1 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar1 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons1 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize2 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton15 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage15 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton16 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage16 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton17 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage17 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton18 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage18 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ScopeXAxisUnitScale scopeXAxisUnitScale1 = new Mitov.PlotLab.ScopeXAxisUnitScale();
            Mitov.PlotLab.DisplayViewSize displayViewSize3 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom1 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange3 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue5 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue6 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin1 = new OpenWire.Proxy.StatePin();
            OpenWire.Proxy.PinList pinList2 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeYAxis scopeYAxis1 = new Mitov.PlotLab.ScopeYAxis();
            Mitov.PlotLab.ScopeAutoScaling scopeAutoScaling1 = new Mitov.PlotLab.ScopeAutoScaling();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace1 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace2 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel2 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground5 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings2 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings2 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings2 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings4 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen5 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings5 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen6 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat2 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks2 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart2 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue2 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange4 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue7 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue8 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue3 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.AxisValue axisValue2 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange5 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue9 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue10 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue4 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks2 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar2 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons2 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize3 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton19 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage19 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton20 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage20 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton21 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage21 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton22 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage22 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayViewSize displayViewSize4 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom2 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange6 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue11 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue12 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin2 = new OpenWire.Proxy.StatePin();
            Mitov.PlotLab.DisplayZoom displayZoom1 = new Mitov.PlotLab.DisplayZoom();
            OpenWire.Proxy.SinkPin sinkPin1 = new OpenWire.Proxy.SinkPin();
            OpenWire.Proxy.SourcePin sourcePin1 = new OpenWire.Proxy.SourcePin();
            Mitov.BasicLab.Threading threading1 = new Mitov.BasicLab.Threading();
            Mitov.BasicLab.ThreadingQueue threadingQueue1 = new Mitov.BasicLab.ThreadingQueue();
            this.Mitov_constellation = new Mitov.PlotLab.Scope(this.components);
            this.checkBox_constellation = new System.Windows.Forms.CheckBox();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.genericComplex_constellation = new Mitov.SignalLab.GenericComplex(this.components);
            this.timer_constellation = new System.Windows.Forms.Timer(this.components);
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.panel1 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.label_freq_dBm = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.Mitov_constellation)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.genericComplex_constellation)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // Mitov_constellation
            // 
            this.Mitov_constellation.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeChannel1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeChannel1.InternalData")));
            scopeChannel1.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel1.Name = "Points";
            scopePoints1.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            vclPen1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen1.InternalData")));
            vclPen1.Width = 0;
            scopePoints1.Pen = vclPen1;
            scopePoints1.Size = ((uint)(3u));
            scopeChannel1.Points = scopePoints1;
            scopeChannel1.XAxisIndex = 0;
            scopeChannel1.YAxisIndex = 0;
            this.Mitov_constellation.Channels.AddRange(new Mitov.PlotLab.ScopeChannel[] {
            scopeChannel1});
            displayViewBackground1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeDataView1.Background = displayViewBackground1;
            vclPen2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen2.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen2.InternalData")));
            vclPen2.Width = 0;
            displayGridLineSettings1.Pen = vclPen2;
            scopeDataView1.Border = displayGridLineSettings1;
            this.Mitov_constellation.DataView = scopeDataView1;
            channelItemHighlighting1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.ChannelLinks = channelItemHighlighting1;
            channelItemHighlighting2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Channels = channelItemHighlighting2;
            displayItemHighlighting1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.CursorLinks = displayItemHighlighting1;
            displayItemHighlighting2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Cursors = displayItemHighlighting2;
            displayItemHighlighting3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Ellipses = displayItemHighlighting3;
            displayItemHighlighting4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Labels = displayItemHighlighting4;
            displayItemHighlighting5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Markers = displayItemHighlighting5;
            channelMouseHitPoint1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            optionalLabel1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            channelMouseHitPoint1.PointLabel = optionalLabel1;
            dataChartHighlighting1.MouseHitPoint = channelMouseHitPoint1;
            displayItemHighlighting6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting1.Zones = displayItemHighlighting6;
            this.Mitov_constellation.Highlighting = dataChartHighlighting1;
            pinList1.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("pinList1.ConnectionData")));
            this.Mitov_constellation.InputPins = pinList1;
            this.Mitov_constellation.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("Mitov_constellation.InternalData")));
            displayViewBackground2.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeLegendView1.Background = displayViewBackground2;
            legendViewButtonSettings1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.Cursor = System.Windows.Forms.Cursors.Default;
            legendViewButtonSettings1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings1.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeLegendView1.Buttons = legendViewButtonSettings1;
            displayLabel1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup1.Caption = displayLabel1;
            legendGroup1.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.ChannelLinks = legendGroup1;
            displayLabel2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup2.Caption = displayLabel2;
            legendGroup2.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.Channels = legendGroup2;
            displayLabel3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup3.Caption = displayLabel3;
            legendGroup3.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.CursorLinks = legendGroup3;
            displayLabel4.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup4.Caption = displayLabel4;
            legendGroup4.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.Cursors = legendGroup4;
            displayLabel5.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup5.Caption = displayLabel5;
            legendGroup5.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.Ellipses = legendGroup5;
            scopeLegendView1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            scopeLegendView1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeLegendView1.InternalData")));
            displayLabel6.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup6.Caption = displayLabel6;
            legendGroup6.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.Labels = legendGroup6;
            displayLabel7.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup7.Caption = displayLabel7;
            legendGroup7.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.MarkerGroups = legendGroup7;
            displayViewSize1.Size = ((uint)(100u));
            scopeLegendView1.ViewSize = displayViewSize1;
            displayLabel8.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup8.Caption = displayLabel8;
            legendGroup8.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView1.Zones = legendGroup8;
            this.Mitov_constellation.Legend = scopeLegendView1;
            this.Mitov_constellation.Location = new System.Drawing.Point(0, 0);
            this.Mitov_constellation.Name = "Mitov_constellation";
            this.Mitov_constellation.RefreshInterval = ((uint)(100u));
            this.Mitov_constellation.Size = new System.Drawing.Size(438, 356);
            this.Mitov_constellation.SizeLimit = ((uint)(0u));
            this.Mitov_constellation.TabIndex = 0;
            this.Mitov_constellation.Text = "scope1";
            displayViewBackground3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayTitle1.Background = displayViewBackground3;
            displayTitle1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 21, 1);
            displayTitle1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("displayTitle1.InternalData")));
            displayTitle1.Text = "Фазове сузір\'я";
            displayViewSize2.Size = ((uint)(100u));
            displayTitle1.ViewSize = displayViewSize2;
            this.Mitov_constellation.Title = displayTitle1;
            displayToolBar1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar1.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayToolBarButton1.Image = displayToolBarButtonImage1;
            displayToolBarButton1.Visible = false;
            displayToolBarButtons1.Copy = displayToolBarButton1;
            displayToolBarButton2.Image = displayToolBarButtonImage2;
            displayToolBarButton2.Visible = false;
            displayToolBarButtons1.Hold = displayToolBarButton2;
            displayToolBarButton3.Image = displayToolBarButtonImage3;
            displayToolBarButton3.Visible = false;
            displayToolBarButtons1.PanMode = displayToolBarButton3;
            displayToolBarButton4.Image = displayToolBarButtonImage4;
            displayToolBarButton4.Visible = false;
            displayToolBarButtons1.Print = displayToolBarButton4;
            displayToolBarButton5.Image = displayToolBarButtonImage5;
            displayToolBarButton5.Visible = false;
            displayToolBarButtons1.Run = displayToolBarButton5;
            displayToolBarButton6.Image = displayToolBarButtonImage6;
            displayToolBarButton6.Visible = false;
            displayToolBarButtons1.Save = displayToolBarButton6;
            displayToolBarButton7.Image = displayToolBarButtonImage7;
            displayToolBarButton7.Visible = false;
            displayToolBarButtons1.Setup = displayToolBarButton7;
            toolBarButtonSize1.Height = 20;
            toolBarButtonSize1.Width = 20;
            displayToolBarButtons1.Size = toolBarButtonSize1;
            displayToolBarButton8.Image = displayToolBarButtonImage8;
            displayToolBarButton8.Visible = false;
            displayToolBarButtons1.XYZoomOn = displayToolBarButton8;
            displayToolBarButton9.Image = displayToolBarButtonImage9;
            displayToolBarButton9.Visible = false;
            displayToolBarButtons1.ZoomIn = displayToolBarButton9;
            displayToolBarButton10.Image = displayToolBarButtonImage10;
            displayToolBarButton10.Visible = false;
            displayToolBarButtons1.ZoomMode = displayToolBarButton10;
            displayToolBarButton11.Image = displayToolBarButtonImage11;
            displayToolBarButton11.Visible = false;
            displayToolBarButtons1.ZoomNext = displayToolBarButton11;
            displayToolBarButton12.Image = displayToolBarButtonImage12;
            displayToolBarButtons1.ZoomOff = displayToolBarButton12;
            displayToolBarButton13.Image = displayToolBarButtonImage13;
            displayToolBarButton13.Visible = false;
            displayToolBarButtons1.ZoomOut = displayToolBarButton13;
            displayToolBarButton14.Image = displayToolBarButtonImage14;
            displayToolBarButton14.Visible = false;
            displayToolBarButtons1.ZoomPrevious = displayToolBarButton14;
            displayToolBar1.Buttons = displayToolBarButtons1;
            displayToolBar1.CountRows = 1;
            displayToolBar1.Cursor = System.Windows.Forms.Cursors.Default;
            displayToolBar1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayToolBar1.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar1.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar1.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar1.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar1.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            toolBarPosition1.CX = 5;
            toolBarPosition1.CY = 5;
            toolBarPosition1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("toolBarPosition1.InternalData")));
            displayToolBar1.Position = toolBarPosition1;
            this.Mitov_constellation.ToolBar = displayToolBar1;
            displayTrails1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            displayTrails1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            this.Mitov_constellation.Trails = displayTrails1;
            displayTitleLabel1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            displayTitleLabel1.Text = "I";
            displayTitleLabel1.Visible = false;
            scopeXAxis1.AxisLabel = displayTitleLabel1;
            displayViewBackground4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis1.Background = displayViewBackground4;
            viewButtonSettings1.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings1.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings1.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings1.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings1.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis1.Button = viewButtonSettings1;
            scopeXAxis1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis1.CursorSettings = displayAxisCursorSettings1;
            vclPen3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen3.InternalData")));
            vclPen3.Width = 0;
            displayGridLineSettings2.Pen = vclPen3;
            displayGridLineSettings2.Visible = false;
            displayGridDirectionalLinesSettings1.Lines = displayGridLineSettings2;
            vclPen4.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen4.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen4.InternalData")));
            vclPen4.Width = 0;
            displayGridLineSettings3.Pen = vclPen4;
            displayGridDirectionalLinesSettings1.ZeroLine = displayGridLineSettings3;
            scopeXAxis1.DataView = displayGridDirectionalLinesSettings1;
            scopeXAxis1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            axisFormat1.Precision = 3;
            scopeXAxis1.Format = axisFormat1;
            scopeXAxis1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeXAxis1.InternalData")));
            ticksStart1.StartFrom = 0D;
            majorTicks1.StartFrom = ticksStart1;
            majorTicks1.Step = 10D;
            scopeXAxis1.MajorTicks = majorTicks1;
            maxAxisValue1.DataValue = 128D;
            displayOptionalValue1.Enabled = false;
            displayOptionalValue1.Value = 1000D;
            displayValueRange1.High = displayOptionalValue1;
            displayOptionalValue2.Enabled = false;
            displayOptionalValue2.Value = -1000D;
            displayValueRange1.Low = displayOptionalValue2;
            maxAxisValue1.Range = displayValueRange1;
            basicAxisValue1.Value = 1024D;
            maxAxisValue1.Tick = basicAxisValue1;
            maxAxisValue1.Value = 128D;
            scopeXAxis1.Max = maxAxisValue1;
            scopeMaxSample1.Value = ((uint)(1024u));
            scopeXAxis1.MaxSample = scopeMaxSample1;
            axisValue1.DataValue = -128D;
            displayOptionalValue3.Enabled = false;
            displayOptionalValue3.Value = 1000D;
            displayValueRange2.High = displayOptionalValue3;
            displayOptionalValue4.Enabled = false;
            displayOptionalValue4.Value = -1000D;
            displayValueRange2.Low = displayOptionalValue4;
            axisValue1.Range = displayValueRange2;
            basicAxisValue2.Value = 0D;
            axisValue1.Tick = basicAxisValue2;
            axisValue1.Value = -128D;
            scopeXAxis1.Min = axisValue1;
            scopeXAxis1.MinorTicks = minorTicks1;
            axisToolBar1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar1.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons1.Size = toolBarButtonSize2;
            displayToolBarButton15.Image = displayToolBarButtonImage15;
            axisToolBarButtons1.ZoomIn = displayToolBarButton15;
            displayToolBarButton16.Image = displayToolBarButtonImage16;
            axisToolBarButtons1.ZoomOff = displayToolBarButton16;
            displayToolBarButton17.Image = displayToolBarButtonImage17;
            axisToolBarButtons1.ZoomOneDir = displayToolBarButton17;
            displayToolBarButton18.Image = displayToolBarButtonImage18;
            axisToolBarButtons1.ZoomOut = displayToolBarButton18;
            axisToolBar1.Buttons = axisToolBarButtons1;
            axisToolBar1.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar1.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar1.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar1.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar1.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar1.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar1.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar1.Visible = false;
            scopeXAxis1.ToolBar = axisToolBar1;
            scopeXAxis1.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis1.UnitScale = scopeXAxisUnitScale1;
            displayViewSize3.Size = ((uint)(100u));
            scopeXAxis1.ViewSize = displayViewSize3;
            displayOptionalValue5.Enabled = false;
            displayOptionalValue5.Value = 100000000D;
            displayValueRange3.High = displayOptionalValue5;
            displayOptionalValue6.Enabled = true;
            displayOptionalValue6.Value = 1E-07D;
            displayValueRange3.Low = displayOptionalValue6;
            displayAxisZoom1.Range = displayValueRange3;
            scopeXAxis1.Zooming = displayAxisZoom1;
            scopeXAxis1.ZoomPin = statePin1;
            this.Mitov_constellation.XAxis = scopeXAxis1;
            this.Mitov_constellation.XInputPins = pinList2;
            scopeAutoScaling1.MaxHistory = ((uint)(20u));
            scopeAutoScalingSpace1.Space = ((uint)(20u));
            scopeAutoScalingSpace1.Threshold = ((uint)(10u));
            scopeAutoScaling1.SpaceAbove = scopeAutoScalingSpace1;
            scopeAutoScalingSpace2.Space = ((uint)(20u));
            scopeAutoScalingSpace2.Threshold = ((uint)(10u));
            scopeAutoScaling1.SpaceBelow = scopeAutoScalingSpace2;
            scopeYAxis1.AutoScaling = scopeAutoScaling1;
            displayTitleLabel2.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            displayTitleLabel2.Text = "Q";
            displayTitleLabel2.Visible = false;
            scopeYAxis1.AxisLabel = displayTitleLabel2;
            displayViewBackground5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeYAxis1.Background = displayViewBackground5;
            viewButtonSettings2.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings2.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings2.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis1.Button = viewButtonSettings2;
            scopeYAxis1.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeYAxis1.CursorSettings = displayAxisCursorSettings2;
            vclPen5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            vclPen5.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen5.InternalData")));
            vclPen5.Width = 0;
            displayGridLineSettings4.Pen = vclPen5;
            displayGridLineSettings4.Visible = false;
            displayGridDirectionalLinesSettings2.Lines = displayGridLineSettings4;
            vclPen6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(139)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen6.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen6.InternalData")));
            vclPen6.Width = 0;
            displayGridLineSettings5.Pen = vclPen6;
            displayGridDirectionalLinesSettings2.ZeroLine = displayGridLineSettings5;
            scopeYAxis1.DataView = displayGridDirectionalLinesSettings2;
            scopeYAxis1.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            axisFormat2.Precision = 3;
            scopeYAxis1.Format = axisFormat2;
            scopeYAxis1.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeYAxis1.InternalData")));
            ticksStart2.StartFrom = 0D;
            majorTicks2.StartFrom = ticksStart2;
            majorTicks2.Step = 10D;
            scopeYAxis1.MajorTicks = majorTicks2;
            maxAxisValue2.DataValue = 128D;
            displayOptionalValue7.Enabled = false;
            displayOptionalValue7.Value = 1000D;
            displayValueRange4.High = displayOptionalValue7;
            displayOptionalValue8.Enabled = false;
            displayOptionalValue8.Value = -1000D;
            displayValueRange4.Low = displayOptionalValue8;
            maxAxisValue2.Range = displayValueRange4;
            basicAxisValue3.Value = 0D;
            maxAxisValue2.Tick = basicAxisValue3;
            maxAxisValue2.Value = 128D;
            scopeYAxis1.Max = maxAxisValue2;
            axisValue2.DataValue = -128D;
            displayOptionalValue9.Enabled = false;
            displayOptionalValue9.Value = 1000D;
            displayValueRange5.High = displayOptionalValue9;
            displayOptionalValue10.Enabled = false;
            displayOptionalValue10.Value = -1000D;
            displayValueRange5.Low = displayOptionalValue10;
            axisValue2.Range = displayValueRange5;
            basicAxisValue4.Value = 0D;
            axisValue2.Tick = basicAxisValue4;
            axisValue2.Value = -128D;
            scopeYAxis1.Min = axisValue2;
            scopeYAxis1.MinorTicks = minorTicks2;
            axisToolBar2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar2.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons2.Size = toolBarButtonSize3;
            displayToolBarButton19.Image = displayToolBarButtonImage19;
            axisToolBarButtons2.ZoomIn = displayToolBarButton19;
            displayToolBarButton20.Image = displayToolBarButtonImage20;
            axisToolBarButtons2.ZoomOff = displayToolBarButton20;
            displayToolBarButton21.Image = displayToolBarButtonImage21;
            axisToolBarButtons2.ZoomOneDir = displayToolBarButton21;
            displayToolBarButton22.Image = displayToolBarButtonImage22;
            axisToolBarButtons2.ZoomOut = displayToolBarButton22;
            axisToolBar2.Buttons = axisToolBarButtons2;
            axisToolBar2.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar2.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar2.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar2.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar2.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar2.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar2.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar2.Visible = false;
            scopeYAxis1.ToolBar = axisToolBar2;
            scopeYAxis1.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayViewSize4.Size = ((uint)(100u));
            scopeYAxis1.ViewSize = displayViewSize4;
            displayOptionalValue11.Enabled = false;
            displayOptionalValue11.Value = 100000000D;
            displayValueRange6.High = displayOptionalValue11;
            displayOptionalValue12.Enabled = true;
            displayOptionalValue12.Value = 1E-07D;
            displayValueRange6.Low = displayOptionalValue12;
            displayAxisZoom2.Range = displayValueRange6;
            scopeYAxis1.Zooming = displayAxisZoom2;
            scopeYAxis1.ZoomPin = statePin2;
            this.Mitov_constellation.YAxis = scopeYAxis1;
            displayZoom1.HoldOnZoom = false;
            displayZoom1.SelectionColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Mitov_constellation.Zooming = displayZoom1;
            // 
            // checkBox_constellation
            // 
            this.checkBox_constellation.AutoSize = true;
            this.checkBox_constellation.BackColor = System.Drawing.Color.Black;
            this.checkBox_constellation.Checked = true;
            this.checkBox_constellation.CheckState = System.Windows.Forms.CheckState.Checked;
            this.checkBox_constellation.Cursor = System.Windows.Forms.Cursors.Default;
            this.checkBox_constellation.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.checkBox_constellation.FlatAppearance.BorderSize = 0;
            this.checkBox_constellation.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.checkBox_constellation.ForeColor = System.Drawing.Color.DarkRed;
            this.checkBox_constellation.Location = new System.Drawing.Point(376, 335);
            this.checkBox_constellation.Name = "checkBox_constellation";
            this.checkBox_constellation.Size = new System.Drawing.Size(52, 17);
            this.checkBox_constellation.TabIndex = 1;
            this.checkBox_constellation.Text = "on/off";
            this.checkBox_constellation.UseVisualStyleBackColor = false;
            this.checkBox_constellation.CheckedChanged += new System.EventHandler(this.checkBox_constellation_CheckedChanged);
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "if_78_Stars_183390.ico");
            // 
            // genericComplex_constellation
            // 
            this.genericComplex_constellation.InputPin = sinkPin1;
            sourcePin1.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sourcePin1.ConnectionData")));
            this.genericComplex_constellation.OutputPin = sourcePin1;
            threadingQueue1.Size = ((uint)(15u));
            threading1.Queue = threadingQueue1;
            this.genericComplex_constellation.Threading = threading1;
            // 
            // timer_constellation
            // 
            this.timer_constellation.Interval = 10;
            this.timer_constellation.Tick += new System.EventHandler(this.timer_constellation_Tick);
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Controls.Add(this.label1);
            this.panel1.Controls.Add(this.label_freq_dBm);
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(328, 32);
            this.panel1.TabIndex = 22;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial", 16F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(204)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(135, 1);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(168, 26);
            this.label1.TabIndex = 130;
            this.label1.Text = "Фазове сузір\'я";
            // 
            // label_freq_dBm
            // 
            this.label_freq_dBm.AutoSize = true;
            this.label_freq_dBm.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.label_freq_dBm.Location = new System.Drawing.Point(12, 9);
            this.label_freq_dBm.Name = "label_freq_dBm";
            this.label_freq_dBm.Size = new System.Drawing.Size(0, 13);
            this.label_freq_dBm.TabIndex = 129;
            // 
            // Constellation
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(438, 356);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.checkBox_constellation);
            this.Controls.Add(this.Mitov_constellation);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Constellation";
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Сузір\'я";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Constellation_FormClosing);
            this.Load += new System.EventHandler(this.Constellation_Load);
            ((System.ComponentModel.ISupportInitialize)(this.Mitov_constellation)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.genericComplex_constellation)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Mitov.PlotLab.Scope Mitov_constellation;
        private System.Windows.Forms.CheckBox checkBox_constellation;
        private System.Windows.Forms.ImageList imageList1;
        private Mitov.SignalLab.GenericComplex genericComplex_constellation;
        private System.Windows.Forms.Timer timer_constellation;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label_freq_dBm;
    }
}