namespace demodulation
{
    partial class Exponent
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Mitov.PlotLab.ScopeChannel scopeChannel5 = new Mitov.PlotLab.ScopeChannel();
            Mitov.PlotLab.ScopePoints scopePoints5 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen19 = new Vcl.VclPen();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Exponent));
            Mitov.PlotLab.ScopeChannel scopeChannel6 = new Mitov.PlotLab.ScopeChannel();
            Mitov.PlotLab.ScopePoints scopePoints6 = new Mitov.PlotLab.ScopePoints();
            Vcl.VclPen vclPen20 = new Vcl.VclPen();
            Mitov.PlotLab.ScopeCursor scopeCursor3 = new Mitov.PlotLab.ScopeCursor();
            Mitov.PlotLab.DisplayCursorMouseCursor displayCursorMouseCursor3 = new Mitov.PlotLab.DisplayCursorMouseCursor();
            Mitov.PlotLab.DisplayCursorPosition displayCursorPosition3 = new Mitov.PlotLab.DisplayCursorPosition();
            Mitov.PlotLab.ScopeDataView scopeDataView3 = new Mitov.PlotLab.ScopeDataView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground13 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings15 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen21 = new Vcl.VclPen();
            Mitov.PlotLab.DataChartHighlighting dataChartHighlighting3 = new Mitov.PlotLab.DataChartHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting5 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.ChannelItemHighlighting channelItemHighlighting6 = new Mitov.PlotLab.ChannelItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting13 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting14 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting15 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting16 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting17 = new Mitov.PlotLab.DisplayItemHighlighting();
            Mitov.PlotLab.ChannelMouseHitPoint channelMouseHitPoint3 = new Mitov.PlotLab.ChannelMouseHitPoint();
            Mitov.BasicLab.OptionalLabel optionalLabel3 = new Mitov.BasicLab.OptionalLabel();
            Mitov.PlotLab.DisplayItemHighlighting displayItemHighlighting18 = new Mitov.PlotLab.DisplayItemHighlighting();
            OpenWire.Proxy.PinList pinList5 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeLegendView scopeLegendView3 = new Mitov.PlotLab.ScopeLegendView();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground14 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.LegendViewButtonSettings legendViewButtonSettings3 = new Mitov.PlotLab.LegendViewButtonSettings();
            Mitov.PlotLab.LegendGroup legendGroup17 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel17 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup18 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel18 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup19 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel19 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup20 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel20 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup21 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel21 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup22 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel22 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.LegendGroup legendGroup23 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel23 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayViewSize displayViewSize11 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.LegendGroup legendGroup24 = new Mitov.PlotLab.LegendGroup();
            Mitov.PlotLab.DisplayLabel displayLabel24 = new Mitov.PlotLab.DisplayLabel();
            Mitov.PlotLab.DisplayTitle displayTitle3 = new Mitov.PlotLab.DisplayTitle();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground15 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.DisplayViewSize displayViewSize12 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayToolBar displayToolBar3 = new Mitov.PlotLab.DisplayToolBar();
            Mitov.PlotLab.DisplayToolBarButtons displayToolBarButtons3 = new Mitov.PlotLab.DisplayToolBarButtons();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton53 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage53 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton54 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage54 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton55 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage55 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton56 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage56 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton57 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage57 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton58 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage58 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton59 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage59 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize9 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton60 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage60 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton61 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage61 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton62 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage62 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton63 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage63 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton64 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage64 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton65 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage65 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton66 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage66 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ToolBarPosition toolBarPosition3 = new Mitov.PlotLab.ToolBarPosition();
            Mitov.PlotLab.DisplayTrails displayTrails3 = new Mitov.PlotLab.DisplayTrails();
            Mitov.PlotLab.ScopeXAxis scopeXAxis3 = new Mitov.PlotLab.ScopeXAxis();
            Mitov.PlotLab.ScopeXAxesCollectionItem scopeXAxesCollectionItem3 = new Mitov.PlotLab.ScopeXAxesCollectionItem();
            Mitov.PlotLab.AdditionalScopeXAxis additionalScopeXAxis3 = new Mitov.PlotLab.AdditionalScopeXAxis();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel7 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground16 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings7 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings7 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings7 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings16 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen22 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings17 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen23 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat7 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks7 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart7 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue7 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange19 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue37 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue38 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue13 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.ScopeMaxSample scopeMaxSample5 = new Mitov.PlotLab.ScopeMaxSample();
            Mitov.PlotLab.AxisValue axisValue7 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange20 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue39 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue40 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue14 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks7 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar7 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons7 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize10 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton67 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage67 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton68 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage68 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton69 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage69 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton70 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage70 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ScopeXAxisUnitScale scopeXAxisUnitScale5 = new Mitov.PlotLab.ScopeXAxisUnitScale();
            Mitov.PlotLab.DisplayViewSize displayViewSize13 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom7 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange21 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue41 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue42 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin7 = new OpenWire.Proxy.StatePin();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel8 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground17 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings8 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings8 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings8 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings18 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen24 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings19 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen25 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat8 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks8 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart8 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue8 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange22 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue43 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue44 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue15 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.ScopeMaxSample scopeMaxSample6 = new Mitov.PlotLab.ScopeMaxSample();
            Mitov.PlotLab.AxisValue axisValue8 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange23 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue45 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue46 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue16 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks8 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar8 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons8 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize11 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton71 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage71 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton72 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage72 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton73 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage73 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton74 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage74 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.ScopeXAxisUnitScale scopeXAxisUnitScale6 = new Mitov.PlotLab.ScopeXAxisUnitScale();
            Mitov.PlotLab.DisplayViewSize displayViewSize14 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom8 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange24 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue47 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue48 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin8 = new OpenWire.Proxy.StatePin();
            OpenWire.Proxy.PinList pinList6 = new OpenWire.Proxy.PinList();
            Mitov.PlotLab.ScopeYAxis scopeYAxis3 = new Mitov.PlotLab.ScopeYAxis();
            Mitov.PlotLab.ScopeAutoScaling scopeAutoScaling3 = new Mitov.PlotLab.ScopeAutoScaling();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace5 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.ScopeAutoScalingSpace scopeAutoScalingSpace6 = new Mitov.PlotLab.ScopeAutoScalingSpace();
            Mitov.PlotLab.DisplayTitleLabel displayTitleLabel9 = new Mitov.PlotLab.DisplayTitleLabel();
            Mitov.PlotLab.DisplayViewBackground displayViewBackground18 = new Mitov.PlotLab.DisplayViewBackground();
            Mitov.PlotLab.ViewButtonSettings viewButtonSettings9 = new Mitov.PlotLab.ViewButtonSettings();
            Mitov.PlotLab.DisplayAxisCursorSettings displayAxisCursorSettings9 = new Mitov.PlotLab.DisplayAxisCursorSettings();
            Mitov.PlotLab.DisplayGridDirectionalLinesSettings displayGridDirectionalLinesSettings9 = new Mitov.PlotLab.DisplayGridDirectionalLinesSettings();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings20 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen26 = new Vcl.VclPen();
            Mitov.PlotLab.DisplayGridLineSettings displayGridLineSettings21 = new Mitov.PlotLab.DisplayGridLineSettings();
            Vcl.VclPen vclPen27 = new Vcl.VclPen();
            Mitov.PlotLab.AxisFormat axisFormat9 = new Mitov.PlotLab.AxisFormat();
            Mitov.PlotLab.MajorTicks majorTicks9 = new Mitov.PlotLab.MajorTicks();
            Mitov.PlotLab.TicksStart ticksStart9 = new Mitov.PlotLab.TicksStart();
            Mitov.PlotLab.MaxAxisValue maxAxisValue9 = new Mitov.PlotLab.MaxAxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange25 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue49 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue50 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue17 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.AxisValue axisValue9 = new Mitov.PlotLab.AxisValue();
            Mitov.PlotLab.DisplayValueRange displayValueRange26 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue51 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue52 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.BasicAxisValue basicAxisValue18 = new Mitov.PlotLab.BasicAxisValue();
            Mitov.PlotLab.MinorTicks minorTicks9 = new Mitov.PlotLab.MinorTicks();
            Mitov.PlotLab.AxisToolBar axisToolBar9 = new Mitov.PlotLab.AxisToolBar();
            Mitov.PlotLab.AxisToolBarButtons axisToolBarButtons9 = new Mitov.PlotLab.AxisToolBarButtons();
            Mitov.PlotLab.ToolBarButtonSize toolBarButtonSize12 = new Mitov.PlotLab.ToolBarButtonSize();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton75 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage75 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton76 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage76 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton77 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage77 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayToolBarButton displayToolBarButton78 = new Mitov.PlotLab.DisplayToolBarButton();
            Mitov.PlotLab.DisplayToolBarButtonImage displayToolBarButtonImage78 = new Mitov.PlotLab.DisplayToolBarButtonImage();
            Mitov.PlotLab.DisplayViewSize displayViewSize15 = new Mitov.PlotLab.DisplayViewSize();
            Mitov.PlotLab.DisplayAxisZoom displayAxisZoom9 = new Mitov.PlotLab.DisplayAxisZoom();
            Mitov.PlotLab.DisplayValueRange displayValueRange27 = new Mitov.PlotLab.DisplayValueRange();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue53 = new Mitov.PlotLab.DisplayOptionalValue();
            Mitov.PlotLab.DisplayOptionalValue displayOptionalValue54 = new Mitov.PlotLab.DisplayOptionalValue();
            OpenWire.Proxy.StatePin statePin9 = new OpenWire.Proxy.StatePin();
            Mitov.PlotLab.DisplayZoom displayZoom3 = new Mitov.PlotLab.DisplayZoom();
            OpenWire.Proxy.SinkPin sinkPin3 = new OpenWire.Proxy.SinkPin();
            OpenWire.Proxy.SourcePin sourcePin3 = new OpenWire.Proxy.SourcePin();
            Mitov.BasicLab.Threading threading3 = new Mitov.BasicLab.Threading();
            Mitov.BasicLab.ThreadingQueue threadingQueue3 = new Mitov.BasicLab.ThreadingQueue();
            this.MitovScope = new Mitov.PlotLab.Scope(this.components);
            this.panel1 = new System.Windows.Forms.Panel();
            this.label_freq_dBm = new System.Windows.Forms.Label();
            this.checkBox_Exponent = new System.Windows.Forms.CheckBox();
            this.timer_exponent = new System.Windows.Forms.Timer(this.components);
            this.genericReal_exponent = new Mitov.SignalLab.GenericReal(this.components);
            this.timer1 = new System.Windows.Forms.Timer(this.components);
            this.radioButton_moduleX = new System.Windows.Forms.RadioButton();
            this.radioButton_X2 = new System.Windows.Forms.RadioButton();
            this.radioButton_X4 = new System.Windows.Forms.RadioButton();
            this.radioButton_x8 = new System.Windows.Forms.RadioButton();
            ((System.ComponentModel.ISupportInitialize)(this.MitovScope)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.genericReal_exponent)).BeginInit();
            this.SuspendLayout();
            // 
            // MitovScope
            // 
            this.MitovScope.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeChannel5.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel5.Name = "Сигнал";
            scopePoints5.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            vclPen19.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen19.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen19.InternalData")));
            scopePoints5.Pen = vclPen19;
            scopePoints5.Size = ((uint)(3u));
            scopeChannel5.Points = scopePoints5;
            scopeChannel5.XAxisIndex = 0;
            scopeChannel5.YAxisIndex = 0;
            scopeChannel6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeChannel6.MouseCursor = System.Windows.Forms.Cursors.Default;
            scopeChannel6.Name = "Пик";
            scopePoints6.Brush = new Vcl.VclBrush(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0))))), 0);
            scopePoints6.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopePoints6.InternalData")));
            vclPen20.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            vclPen20.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen20.InternalData")));
            scopePoints6.Pen = vclPen20;
            scopePoints6.Size = ((uint)(5u));
            scopePoints6.Visible = true;
            scopeChannel6.Points = scopePoints6;
            scopeChannel6.XAxisIndex = 0;
            scopeChannel6.YAxisIndex = 0;
            this.MitovScope.Channels.AddRange(new Mitov.PlotLab.ScopeChannel[] {
            scopeChannel5,
            scopeChannel6});
            scopeCursor3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayCursorMouseCursor3.Both = System.Windows.Forms.Cursors.Default;
            displayCursorMouseCursor3.Horizontal = System.Windows.Forms.Cursors.Default;
            displayCursorMouseCursor3.Vertical = System.Windows.Forms.Cursors.Default;
            scopeCursor3.MouseCursors = displayCursorMouseCursor3;
            scopeCursor3.Name = "Частота";
            displayCursorPosition3.X = 0D;
            displayCursorPosition3.Y = 0D;
            scopeCursor3.Position = displayCursorPosition3;
            scopeCursor3.XAxisIndex = 0;
            scopeCursor3.YAxisIndex = 0;
            this.MitovScope.Cursors.AddRange(new Mitov.PlotLab.ScopeCursor[] {
            scopeCursor3});
            displayViewBackground13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeDataView3.Background = displayViewBackground13;
            vclPen21.Color = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen21.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen21.InternalData")));
            displayGridLineSettings15.Pen = vclPen21;
            scopeDataView3.Border = displayGridLineSettings15;
            this.MitovScope.DataView = scopeDataView3;
            this.MitovScope.Dock = System.Windows.Forms.DockStyle.Fill;
            channelItemHighlighting5.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.ChannelLinks = channelItemHighlighting5;
            channelItemHighlighting6.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Channels = channelItemHighlighting6;
            displayItemHighlighting13.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.CursorLinks = displayItemHighlighting13;
            displayItemHighlighting14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Cursors = displayItemHighlighting14;
            displayItemHighlighting15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Ellipses = displayItemHighlighting15;
            displayItemHighlighting16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Labels = displayItemHighlighting16;
            displayItemHighlighting17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Markers = displayItemHighlighting17;
            channelMouseHitPoint3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            optionalLabel3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            channelMouseHitPoint3.PointLabel = optionalLabel3;
            dataChartHighlighting3.MouseHitPoint = channelMouseHitPoint3;
            displayItemHighlighting18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            dataChartHighlighting3.Zones = displayItemHighlighting18;
            this.MitovScope.Highlighting = dataChartHighlighting3;
            pinList5.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("pinList5.ConnectionData")));
            this.MitovScope.InputPins = pinList5;
            this.MitovScope.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("MitovScope.InternalData")));
            displayViewBackground14.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeLegendView3.Background = displayViewBackground14;
            legendViewButtonSettings3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.Cursor = System.Windows.Forms.Cursors.Default;
            legendViewButtonSettings3.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            legendViewButtonSettings3.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeLegendView3.Buttons = legendViewButtonSettings3;
            displayLabel17.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup17.Caption = displayLabel17;
            legendGroup17.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.ChannelLinks = legendGroup17;
            displayLabel18.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup18.Caption = displayLabel18;
            legendGroup18.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.Channels = legendGroup18;
            displayLabel19.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup19.Caption = displayLabel19;
            legendGroup19.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.CursorLinks = legendGroup19;
            displayLabel20.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup20.Caption = displayLabel20;
            legendGroup20.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.Cursors = legendGroup20;
            displayLabel21.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup21.Caption = displayLabel21;
            legendGroup21.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.Ellipses = legendGroup21;
            scopeLegendView3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            scopeLegendView3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeLegendView3.InternalData")));
            displayLabel22.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup22.Caption = displayLabel22;
            legendGroup22.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.Labels = legendGroup22;
            displayLabel23.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup23.Caption = displayLabel23;
            legendGroup23.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.MarkerGroups = legendGroup23;
            displayViewSize11.Size = ((uint)(100u));
            scopeLegendView3.ViewSize = displayViewSize11;
            displayLabel24.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            legendGroup24.Caption = displayLabel24;
            legendGroup24.Cursor = System.Windows.Forms.Cursors.Default;
            scopeLegendView3.Zones = legendGroup24;
            this.MitovScope.Legend = scopeLegendView3;
            this.MitovScope.Location = new System.Drawing.Point(0, 0);
            this.MitovScope.Name = "MitovScope";
            this.MitovScope.RefreshInterval = ((uint)(100u));
            this.MitovScope.Size = new System.Drawing.Size(688, 356);
            this.MitovScope.SizeLimit = ((uint)(0u));
            this.MitovScope.TabIndex = 20;
            this.MitovScope.Text = "scope";
            displayViewBackground15.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayTitle3.Background = displayViewBackground15;
            displayTitle3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 21, 1);
            displayTitle3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("displayTitle3.InternalData")));
            displayTitle3.Text = "Піднесення до ступеня";
            displayViewSize12.Size = ((uint)(100u));
            displayTitle3.ViewSize = displayViewSize12;
            this.MitovScope.Title = displayTitle3;
            displayToolBar3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(0)))));
            displayToolBar3.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayToolBarButton53.Image = displayToolBarButtonImage53;
            displayToolBarButton53.Visible = false;
            displayToolBarButtons3.Copy = displayToolBarButton53;
            displayToolBarButton54.Image = displayToolBarButtonImage54;
            displayToolBarButton54.Visible = false;
            displayToolBarButtons3.Hold = displayToolBarButton54;
            displayToolBarButton55.Image = displayToolBarButtonImage55;
            displayToolBarButton55.Visible = false;
            displayToolBarButtons3.PanMode = displayToolBarButton55;
            displayToolBarButton56.Image = displayToolBarButtonImage56;
            displayToolBarButton56.Visible = false;
            displayToolBarButtons3.Print = displayToolBarButton56;
            displayToolBarButton57.Image = displayToolBarButtonImage57;
            displayToolBarButton57.Visible = false;
            displayToolBarButtons3.Run = displayToolBarButton57;
            displayToolBarButton58.Image = displayToolBarButtonImage58;
            displayToolBarButton58.Visible = false;
            displayToolBarButtons3.Save = displayToolBarButton58;
            displayToolBarButton59.Image = displayToolBarButtonImage59;
            displayToolBarButton59.Visible = false;
            displayToolBarButtons3.Setup = displayToolBarButton59;
            toolBarButtonSize9.Height = 25;
            toolBarButtonSize9.Width = 25;
            displayToolBarButtons3.Size = toolBarButtonSize9;
            displayToolBarButton60.Image = displayToolBarButtonImage60;
            displayToolBarButton60.Visible = false;
            displayToolBarButtons3.XYZoomOn = displayToolBarButton60;
            displayToolBarButton61.Image = displayToolBarButtonImage61;
            displayToolBarButton61.Visible = false;
            displayToolBarButtons3.ZoomIn = displayToolBarButton61;
            displayToolBarButton62.Image = displayToolBarButtonImage62;
            displayToolBarButton62.Visible = false;
            displayToolBarButtons3.ZoomMode = displayToolBarButton62;
            displayToolBarButton63.Image = displayToolBarButtonImage63;
            displayToolBarButton63.Visible = false;
            displayToolBarButtons3.ZoomNext = displayToolBarButton63;
            displayToolBarButton64.Image = displayToolBarButtonImage64;
            displayToolBarButtons3.ZoomOff = displayToolBarButton64;
            displayToolBarButton65.Image = displayToolBarButtonImage65;
            displayToolBarButton65.Visible = false;
            displayToolBarButtons3.ZoomOut = displayToolBarButton65;
            displayToolBarButton66.Image = displayToolBarButtonImage66;
            displayToolBarButton66.Visible = false;
            displayToolBarButtons3.ZoomPrevious = displayToolBarButton66;
            displayToolBar3.Buttons = displayToolBarButtons3;
            displayToolBar3.Cursor = System.Windows.Forms.Cursors.Default;
            displayToolBar3.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(0)))));
            displayToolBar3.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar3.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar3.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            displayToolBar3.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            displayToolBar3.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(140)))), ((int)(((byte)(0)))));
            toolBarPosition3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("toolBarPosition3.InternalData")));
            displayToolBar3.Position = toolBarPosition3;
            this.MitovScope.ToolBar = displayToolBar3;
            displayTrails3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            displayTrails3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            this.MitovScope.Trails = displayTrails3;
            displayTitleLabel7.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            displayTitleLabel7.Text = "X Axis 1";
            displayTitleLabel7.Visible = false;
            additionalScopeXAxis3.AxisLabel = displayTitleLabel7;
            displayViewBackground16.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            additionalScopeXAxis3.Background = displayViewBackground16;
            viewButtonSettings7.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings7.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings7.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings7.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings7.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            additionalScopeXAxis3.Button = viewButtonSettings7;
            additionalScopeXAxis3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            additionalScopeXAxis3.CursorSettings = displayAxisCursorSettings7;
            vclPen22.Color = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
            vclPen22.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen22.InternalData")));
            displayGridLineSettings16.Pen = vclPen22;
            displayGridLineSettings16.Visible = false;
            displayGridDirectionalLinesSettings7.Lines = displayGridLineSettings16;
            vclPen23.Color = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            vclPen23.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen23.InternalData")));
            displayGridLineSettings17.Pen = vclPen23;
            displayGridLineSettings17.Visible = false;
            displayGridDirectionalLinesSettings7.ZeroLine = displayGridLineSettings17;
            additionalScopeXAxis3.DataView = displayGridDirectionalLinesSettings7;
            additionalScopeXAxis3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            axisFormat7.Precision = 3;
            additionalScopeXAxis3.Format = axisFormat7;
            additionalScopeXAxis3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("additionalScopeXAxis3.InternalData")));
            ticksStart7.StartFrom = 0D;
            majorTicks7.StartFrom = ticksStart7;
            majorTicks7.Step = 10D;
            additionalScopeXAxis3.MajorTicks = majorTicks7;
            maxAxisValue7.AutoScale = false;
            maxAxisValue7.DataValue = 1024D;
            displayOptionalValue37.Enabled = false;
            displayOptionalValue37.Value = 1000D;
            displayValueRange19.High = displayOptionalValue37;
            displayOptionalValue38.Enabled = false;
            displayOptionalValue38.Value = -1000D;
            displayValueRange19.Low = displayOptionalValue38;
            maxAxisValue7.Range = displayValueRange19;
            basicAxisValue13.AutoScale = false;
            basicAxisValue13.Value = 1024D;
            maxAxisValue7.Tick = basicAxisValue13;
            maxAxisValue7.Value = 1024D;
            additionalScopeXAxis3.Max = maxAxisValue7;
            scopeMaxSample5.Value = ((uint)(1024u));
            additionalScopeXAxis3.MaxSample = scopeMaxSample5;
            axisValue7.AutoScale = false;
            axisValue7.DataValue = 0D;
            displayOptionalValue39.Enabled = false;
            displayOptionalValue39.Value = 1000D;
            displayValueRange20.High = displayOptionalValue39;
            displayOptionalValue40.Enabled = false;
            displayOptionalValue40.Value = -1000D;
            displayValueRange20.Low = displayOptionalValue40;
            axisValue7.Range = displayValueRange20;
            basicAxisValue14.AutoScale = false;
            basicAxisValue14.Value = 0D;
            axisValue7.Tick = basicAxisValue14;
            axisValue7.Value = 0D;
            additionalScopeXAxis3.Min = axisValue7;
            additionalScopeXAxis3.MinorTicks = minorTicks7;
            axisToolBar7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar7.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons7.Size = toolBarButtonSize10;
            displayToolBarButton67.Image = displayToolBarButtonImage67;
            axisToolBarButtons7.ZoomIn = displayToolBarButton67;
            displayToolBarButton68.Image = displayToolBarButtonImage68;
            axisToolBarButtons7.ZoomOff = displayToolBarButton68;
            displayToolBarButton69.Image = displayToolBarButtonImage69;
            axisToolBarButtons7.ZoomOneDir = displayToolBarButton69;
            displayToolBarButton70.Image = displayToolBarButtonImage70;
            axisToolBarButtons7.ZoomOut = displayToolBarButton70;
            axisToolBar7.Buttons = axisToolBarButtons7;
            axisToolBar7.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar7.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar7.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar7.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar7.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar7.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar7.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar7.Visible = false;
            additionalScopeXAxis3.ToolBar = axisToolBar7;
            additionalScopeXAxis3.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            additionalScopeXAxis3.UnitScale = scopeXAxisUnitScale5;
            displayViewSize13.Size = ((uint)(100u));
            additionalScopeXAxis3.ViewSize = displayViewSize13;
            displayOptionalValue41.Enabled = false;
            displayOptionalValue41.Value = 100000000D;
            displayValueRange21.High = displayOptionalValue41;
            displayOptionalValue42.Enabled = true;
            displayOptionalValue42.Value = 1E-07D;
            displayValueRange21.Low = displayOptionalValue42;
            displayAxisZoom7.Range = displayValueRange21;
            additionalScopeXAxis3.Zooming = displayAxisZoom7;
            additionalScopeXAxis3.ZoomPin = statePin7;
            scopeXAxesCollectionItem3.Axis = additionalScopeXAxis3;
            scopeXAxis3.AdditionalAxes.AddRange(new Mitov.PlotLab.ScopeXAxesCollectionItem[] {
            scopeXAxesCollectionItem3});
            displayTitleLabel8.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            displayTitleLabel8.Text = "Hz";
            scopeXAxis3.AxisLabel = displayTitleLabel8;
            displayViewBackground17.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis3.Background = displayViewBackground17;
            viewButtonSettings8.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings8.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings8.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings8.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings8.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeXAxis3.Button = viewButtonSettings8;
            scopeXAxis3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeXAxis3.CursorSettings = displayAxisCursorSettings8;
            vclPen24.Color = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(105)))), ((int)(((byte)(30)))));
            vclPen24.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen24.InternalData")));
            displayGridLineSettings18.Pen = vclPen24;
            displayGridDirectionalLinesSettings8.Lines = displayGridLineSettings18;
            vclPen25.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen25.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen25.InternalData")));
            displayGridLineSettings19.Pen = vclPen25;
            displayGridDirectionalLinesSettings8.ZeroLine = displayGridLineSettings19;
            scopeXAxis3.DataView = displayGridDirectionalLinesSettings8;
            scopeXAxis3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            axisFormat8.Precision = 3;
            scopeXAxis3.Format = axisFormat8;
            scopeXAxis3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeXAxis3.InternalData")));
            ticksStart8.StartFrom = 0D;
            majorTicks8.StartFrom = ticksStart8;
            majorTicks8.Step = 10D;
            scopeXAxis3.MajorTicks = majorTicks8;
            maxAxisValue8.DataValue = 1024D;
            displayOptionalValue43.Enabled = false;
            displayOptionalValue43.Value = 1000D;
            displayValueRange22.High = displayOptionalValue43;
            displayOptionalValue44.Enabled = false;
            displayOptionalValue44.Value = -1000D;
            displayValueRange22.Low = displayOptionalValue44;
            maxAxisValue8.Range = displayValueRange22;
            basicAxisValue15.Value = 1024D;
            maxAxisValue8.Tick = basicAxisValue15;
            maxAxisValue8.Value = 1024D;
            scopeXAxis3.Max = maxAxisValue8;
            scopeMaxSample6.Value = ((uint)(1024u));
            scopeXAxis3.MaxSample = scopeMaxSample6;
            axisValue8.DataValue = 0D;
            displayOptionalValue45.Enabled = false;
            displayOptionalValue45.Value = 1000D;
            displayValueRange23.High = displayOptionalValue45;
            displayOptionalValue46.Enabled = false;
            displayOptionalValue46.Value = -1000D;
            displayValueRange23.Low = displayOptionalValue46;
            axisValue8.Range = displayValueRange23;
            basicAxisValue16.Value = 0D;
            axisValue8.Tick = basicAxisValue16;
            axisValue8.Value = 0D;
            scopeXAxis3.Min = axisValue8;
            scopeXAxis3.MinorTicks = minorTicks8;
            axisToolBar8.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar8.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons8.Size = toolBarButtonSize11;
            displayToolBarButton71.Image = displayToolBarButtonImage71;
            axisToolBarButtons8.ZoomIn = displayToolBarButton71;
            displayToolBarButton72.Image = displayToolBarButtonImage72;
            axisToolBarButtons8.ZoomOff = displayToolBarButton72;
            displayToolBarButton73.Image = displayToolBarButtonImage73;
            axisToolBarButtons8.ZoomOneDir = displayToolBarButton73;
            displayToolBarButton74.Image = displayToolBarButtonImage74;
            axisToolBarButtons8.ZoomOut = displayToolBarButton74;
            axisToolBar8.Buttons = axisToolBarButtons8;
            axisToolBar8.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar8.DisabledColor = System.Drawing.SystemColors.ActiveBorder;
            axisToolBar8.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar8.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar8.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar8.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar8.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar8.Visible = false;
            scopeXAxis3.ToolBar = axisToolBar8;
            scopeXAxis3.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeXAxis3.UnitScale = scopeXAxisUnitScale6;
            displayViewSize14.Size = ((uint)(100u));
            scopeXAxis3.ViewSize = displayViewSize14;
            scopeXAxis3.Visible = false;
            displayOptionalValue47.Enabled = false;
            displayOptionalValue47.Value = 100000000D;
            displayValueRange24.High = displayOptionalValue47;
            displayOptionalValue48.Enabled = true;
            displayOptionalValue48.Value = 1E-07D;
            displayValueRange24.Low = displayOptionalValue48;
            displayAxisZoom8.Range = displayValueRange24;
            scopeXAxis3.Zooming = displayAxisZoom8;
            scopeXAxis3.ZoomPin = statePin8;
            this.MitovScope.XAxis = scopeXAxis3;
            this.MitovScope.XInputPins = pinList6;
            scopeAutoScaling3.MaxHistory = ((uint)(20u));
            scopeAutoScalingSpace5.Space = ((uint)(20u));
            scopeAutoScalingSpace5.Threshold = ((uint)(10u));
            scopeAutoScaling3.SpaceAbove = scopeAutoScalingSpace5;
            scopeAutoScalingSpace6.Space = ((uint)(20u));
            scopeAutoScalingSpace6.Threshold = ((uint)(10u));
            scopeAutoScaling3.SpaceBelow = scopeAutoScalingSpace6;
            scopeYAxis3.AutoScaling = scopeAutoScaling3;
            displayTitleLabel9.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 13, 1);
            displayTitleLabel9.Text = "dBm";
            scopeYAxis3.AxisLabel = displayTitleLabel9;
            displayViewBackground18.Color = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            scopeYAxis3.Background = displayViewBackground18;
            viewButtonSettings9.Cursor = System.Windows.Forms.Cursors.Default;
            viewButtonSettings9.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings9.MouseDownColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            viewButtonSettings9.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            viewButtonSettings9.MouseOverColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            scopeYAxis3.Button = viewButtonSettings9;
            scopeYAxis3.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            scopeYAxis3.CursorSettings = displayAxisCursorSettings9;
            vclPen26.Color = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(105)))), ((int)(((byte)(30)))));
            vclPen26.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen26.InternalData")));
            displayGridLineSettings20.Pen = vclPen26;
            displayGridDirectionalLinesSettings9.Lines = displayGridLineSettings20;
            vclPen27.Color = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            vclPen27.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("vclPen27.InternalData")));
            displayGridLineSettings21.Pen = vclPen27;
            displayGridDirectionalLinesSettings9.ZeroLine = displayGridLineSettings21;
            scopeYAxis3.DataView = displayGridDirectionalLinesSettings9;
            scopeYAxis3.Font = new Vcl.VclFont(System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255))))), "Arial", 1, 0, true, 11, 0);
            axisFormat9.Precision = 3;
            scopeYAxis3.Format = axisFormat9;
            scopeYAxis3.InternalData = ((Vcl.VclBinaryData)(resources.GetObject("scopeYAxis3.InternalData")));
            ticksStart9.StartFrom = 0D;
            majorTicks9.StartFrom = ticksStart9;
            majorTicks9.Step = 10D;
            scopeYAxis3.MajorTicks = majorTicks9;
            maxAxisValue9.DataValue = 1000D;
            displayOptionalValue49.Enabled = false;
            displayOptionalValue49.Value = 1000D;
            displayValueRange25.High = displayOptionalValue49;
            displayOptionalValue50.Enabled = false;
            displayOptionalValue50.Value = -1000D;
            displayValueRange25.Low = displayOptionalValue50;
            maxAxisValue9.Range = displayValueRange25;
            basicAxisValue17.Value = 0D;
            maxAxisValue9.Tick = basicAxisValue17;
            maxAxisValue9.Value = 1000D;
            scopeYAxis3.Max = maxAxisValue9;
            axisValue9.DataValue = -1000D;
            displayOptionalValue51.Enabled = false;
            displayOptionalValue51.Value = 1000D;
            displayValueRange26.High = displayOptionalValue51;
            displayOptionalValue52.Enabled = false;
            displayOptionalValue52.Value = -1000D;
            displayValueRange26.Low = displayOptionalValue52;
            axisValue9.Range = displayValueRange26;
            basicAxisValue18.Value = 0D;
            axisValue9.Tick = basicAxisValue18;
            axisValue9.Value = -1000D;
            scopeYAxis3.Min = axisValue9;
            scopeYAxis3.MinorTicks = minorTicks9;
            axisToolBar9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar9.ButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            axisToolBarButtons9.Size = toolBarButtonSize12;
            displayToolBarButton75.Image = displayToolBarButtonImage75;
            axisToolBarButtons9.ZoomIn = displayToolBarButton75;
            displayToolBarButton76.Image = displayToolBarButtonImage76;
            axisToolBarButtons9.ZoomOff = displayToolBarButton76;
            displayToolBarButton77.Image = displayToolBarButtonImage77;
            axisToolBarButtons9.ZoomOneDir = displayToolBarButton77;
            displayToolBarButton78.Image = displayToolBarButtonImage78;
            axisToolBarButtons9.ZoomOut = displayToolBarButton78;
            axisToolBar9.Buttons = axisToolBarButtons9;
            axisToolBar9.Cursor = System.Windows.Forms.Cursors.Default;
            axisToolBar9.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar9.GlyphColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar9.MouseDownBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar9.MouseDownButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar9.MouseOverBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            axisToolBar9.MouseOverButtonColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(128)))), ((int)(((byte)(0)))));
            axisToolBar9.Visible = false;
            scopeYAxis3.ToolBar = axisToolBar9;
            scopeYAxis3.TrackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            displayViewSize15.Size = ((uint)(100u));
            scopeYAxis3.ViewSize = displayViewSize15;
            displayOptionalValue53.Enabled = false;
            displayOptionalValue53.Value = 100000000D;
            displayValueRange27.High = displayOptionalValue53;
            displayOptionalValue54.Enabled = true;
            displayOptionalValue54.Value = 1E-07D;
            displayValueRange27.Low = displayOptionalValue54;
            displayAxisZoom9.Range = displayValueRange27;
            scopeYAxis3.Zooming = displayAxisZoom9;
            scopeYAxis3.ZoomPin = statePin9;
            this.MitovScope.YAxis = scopeYAxis3;
            displayZoom3.HoldOnZoom = false;
            displayZoom3.SelectionColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.MitovScope.Zooming = displayZoom3;
            this.MitovScope.MouseMove += new System.Windows.Forms.MouseEventHandler(this.MitovScope_MouseMove);
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.Black;
            this.panel1.Controls.Add(this.label_freq_dBm);
            this.panel1.Location = new System.Drawing.Point(0, -1);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(200, 32);
            this.panel1.TabIndex = 21;
            // 
            // label_freq_dBm
            // 
            this.label_freq_dBm.AutoSize = true;
            this.label_freq_dBm.ForeColor = System.Drawing.SystemColors.ControlLightLight;
            this.label_freq_dBm.Location = new System.Drawing.Point(12, 9);
            this.label_freq_dBm.Name = "label_freq_dBm";
            this.label_freq_dBm.Size = new System.Drawing.Size(0, 13);
            this.label_freq_dBm.TabIndex = 129;
            // 
            // checkBox_Exponent
            // 
            this.checkBox_Exponent.AutoSize = true;
            this.checkBox_Exponent.BackColor = System.Drawing.Color.Black;
            this.checkBox_Exponent.Cursor = System.Windows.Forms.Cursors.Default;
            this.checkBox_Exponent.FlatAppearance.BorderColor = System.Drawing.Color.Black;
            this.checkBox_Exponent.FlatAppearance.BorderSize = 0;
            this.checkBox_Exponent.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.checkBox_Exponent.ForeColor = System.Drawing.Color.DarkRed;
            this.checkBox_Exponent.Location = new System.Drawing.Point(624, 327);
            this.checkBox_Exponent.Name = "checkBox_Exponent";
            this.checkBox_Exponent.Size = new System.Drawing.Size(52, 17);
            this.checkBox_Exponent.TabIndex = 129;
            this.checkBox_Exponent.Text = "on/off";
            this.checkBox_Exponent.UseVisualStyleBackColor = false;
            this.checkBox_Exponent.CheckedChanged += new System.EventHandler(this.checkBox_Exponent_CheckedChanged);
            // 
            // timer_exponent
            // 
            this.timer_exponent.Interval = 10;
            this.timer_exponent.Tick += new System.EventHandler(this.timer_exponent_Tick);
            // 
            // genericReal_exponent
            // 
            this.genericReal_exponent.InputPin = sinkPin3;
            sourcePin3.ConnectionData = ((OpenWire.PinConnections)(resources.GetObject("sourcePin3.ConnectionData")));
            this.genericReal_exponent.OutputPin = sourcePin3;
            threadingQueue3.Size = ((uint)(15u));
            threading3.Queue = threadingQueue3;
            this.genericReal_exponent.Threading = threading3;
            // 
            // timer1
            // 
            this.timer1.Enabled = true;
            this.timer1.Tick += new System.EventHandler(this.timer1_Tick);
            // 
            // radioButton_moduleX
            // 
            this.radioButton_moduleX.AutoSize = true;
            this.radioButton_moduleX.BackColor = System.Drawing.Color.Black;
            this.radioButton_moduleX.Checked = true;
            this.radioButton_moduleX.ForeColor = System.Drawing.Color.White;
            this.radioButton_moduleX.Location = new System.Drawing.Point(628, 146);
            this.radioButton_moduleX.Name = "radioButton_moduleX";
            this.radioButton_moduleX.Size = new System.Drawing.Size(40, 17);
            this.radioButton_moduleX.TabIndex = 130;
            this.radioButton_moduleX.TabStop = true;
            this.radioButton_moduleX.Text = "| x |";
            this.radioButton_moduleX.UseVisualStyleBackColor = false;
            this.radioButton_moduleX.CheckedChanged += new System.EventHandler(this.radioButton_moduleX_CheckedChanged);
            // 
            // radioButton_X2
            // 
            this.radioButton_X2.AutoSize = true;
            this.radioButton_X2.BackColor = System.Drawing.Color.Black;
            this.radioButton_X2.ForeColor = System.Drawing.Color.White;
            this.radioButton_X2.Location = new System.Drawing.Point(628, 169);
            this.radioButton_X2.Name = "radioButton_X2";
            this.radioButton_X2.Size = new System.Drawing.Size(42, 17);
            this.radioButton_X2.TabIndex = 131;
            this.radioButton_X2.Text = "x^2";
            this.radioButton_X2.UseVisualStyleBackColor = false;
            this.radioButton_X2.CheckedChanged += new System.EventHandler(this.radioButton_X2_CheckedChanged);
            // 
            // radioButton_X4
            // 
            this.radioButton_X4.AutoSize = true;
            this.radioButton_X4.BackColor = System.Drawing.Color.Black;
            this.radioButton_X4.ForeColor = System.Drawing.Color.White;
            this.radioButton_X4.Location = new System.Drawing.Point(628, 192);
            this.radioButton_X4.Name = "radioButton_X4";
            this.radioButton_X4.Size = new System.Drawing.Size(42, 17);
            this.radioButton_X4.TabIndex = 132;
            this.radioButton_X4.Text = "x^4";
            this.radioButton_X4.UseVisualStyleBackColor = false;
            this.radioButton_X4.CheckedChanged += new System.EventHandler(this.radioButton_X4_CheckedChanged);
            // 
            // radioButton_x8
            // 
            this.radioButton_x8.AutoSize = true;
            this.radioButton_x8.BackColor = System.Drawing.Color.Black;
            this.radioButton_x8.ForeColor = System.Drawing.Color.White;
            this.radioButton_x8.Location = new System.Drawing.Point(628, 215);
            this.radioButton_x8.Name = "radioButton_x8";
            this.radioButton_x8.Size = new System.Drawing.Size(42, 17);
            this.radioButton_x8.TabIndex = 133;
            this.radioButton_x8.Text = "x^8";
            this.radioButton_x8.UseVisualStyleBackColor = false;
            this.radioButton_x8.CheckedChanged += new System.EventHandler(this.radioButton_x8_CheckedChanged);
            // 
            // Exponent
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(688, 356);
            this.Controls.Add(this.radioButton_x8);
            this.Controls.Add(this.radioButton_X4);
            this.Controls.Add(this.radioButton_X2);
            this.Controls.Add(this.radioButton_moduleX);
            this.Controls.Add(this.checkBox_Exponent);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.MitovScope);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Exponent";
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Exponent";
            this.Load += new System.EventHandler(this.Exponent_Load);
            ((System.ComponentModel.ISupportInitialize)(this.MitovScope)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.genericReal_exponent)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Mitov.PlotLab.Scope MitovScope;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label_freq_dBm;
        private System.Windows.Forms.CheckBox checkBox_Exponent;
        private System.Windows.Forms.Timer timer_exponent;
        private Mitov.SignalLab.GenericReal genericReal_exponent;
        private System.Windows.Forms.Timer timer1;
        private System.Windows.Forms.RadioButton radioButton_moduleX;
        private System.Windows.Forms.RadioButton radioButton_X2;
        private System.Windows.Forms.RadioButton radioButton_X4;
        private System.Windows.Forms.RadioButton radioButton_x8;
    }
}